/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/models/blck.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function Blck(props) {
  const { nodes, materials } = useGLTF('./models/blck.glb')
  const groupRef = useRef();

  useFrame((state, delta) => {
    //groupRef.current.rotation.x += 0.01
    groupRef.current.rotation.y += 0.02 
  })

  return (
    <group {...props} dispose={null} ref={groupRef}>
      <mesh geometry={nodes['3d_Final'].geometry} material={nodes['3d_Final'].material} />
    </group>
  )
}

useGLTF.preload('./models/blck.glb')
